# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
    homeassistant.components.lightmap: debug

panel_custom:
  - name: light-map-panel
    url_path: light-map
    sidebar_title: Light Map
    sidebar_icon: mdi:map
    module_url: /local/light-map-panel.js
    config:
      hello: world

# Define media directories here
homeassistant:
  media_dirs:
    local: /workspaces/home-assistant-group5/config/media

sensor:
  - platform: template
    sensors:
      mock_light_sensor:
        friendly_name: "mock_sensor_1"
        unit_of_measurement: "lux"
        value_template: >
          {% set time = now().hour %}
          {% if time >= 6 and time < 18 %}
            {{ range(500, 1000) | random }}
          {% else %}
            {{ range(0, 300) | random }}
          {% endif %}
      mock_light_sensor_2:
        friendly_name: "mock_sensor_2"
        unit_of_measurement: "lux"
        value_template: >
          {% set time = now().hour %}
          {% if time >= 6 and time < 18 %}
            {{ range(500, 1000) | random }}
          {% else %}
            {{ range(0, 300) | random }}
          {% endif %}

mqtt:
  sensor:
    - name: "test_real_sensor_1"
      state_topic: "home/test1"
      unit_of_measurement: "lux"
      value_template: "{{ value | float }}"
    - name: "test_real_sensor_2"
      state_topic: "home/test2"
      unit_of_measurement: "lux"
      value_template: "{{ value | float }}"

automation:
  - alias: Switch to real Sensor when MQTT is available
    trigger:
      - platform: state
        entity_id: sensor.real_light_sensor
        from: 'unavailable'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.light_sensor_source
          option: Real

lightmap:
  gemini_api_key: !secret gemini_api_key
