# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

panel_custom:
  - name: light-map-panel
    url_path: light-map
    sidebar_title: Light Map
    sidebar_icon: mdi:map
    module_url: /local/light-map-panel.js
    config:
      hello: world

sensor:
  - platform: template
    sensors:
      test_sensor:
        unique_id: "test_sensor_unique_id_1"
        friendly_name: "Test Sensor"
        unit_of_measurement: "lux"
        value_template: "{{ 100 }}"
      test_sensor_2:
        unique_id: "test_sensor_unique_id_2"
        friendly_name: "Test Sensor 2"
        unit_of_measurement: "lux"
        value_template: "{{ 3000 }}"
